name: Workflow Name

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Set up Google Cloud credentials
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: <workload_identity_provider_value>
          # or
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      # Rest of the workflow steps...
